# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Desktop/Sources-On_Sat/mercury_kx1_top.xdc

# XDC: imports/Desktop/Sources/Constraints/timing.xdc

# IP: ip/SD_Out_FIFO/SD_Out_FIFO.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SD_Out_FIFO || ORIG_REF_NAME==SD_Out_FIFO}]

# IP: ip/Signed_Mult/Signed_Mult.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Signed_Mult || ORIG_REF_NAME==Signed_Mult}]

# IP: ip/Unsigned_Mult/Unsigned_Mult.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Unsigned_Mult || ORIG_REF_NAME==Unsigned_Mult}]

# IP: ip/ARM_FIFO_in/ARM_FIFO_in.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_FIFO_in || ORIG_REF_NAME==ARM_FIFO_in}]

# IP: ip/ARM_FIFO_out/ARM_FIFO_out.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ARM_FIFO_out || ORIG_REF_NAME==ARM_FIFO_out}]

# IP: ip/sem_0/sem_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sem_0 || ORIG_REF_NAME==sem_0}]

# IP: ip/Master_Clock_Divider/Master_Clock_Divider.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Master_Clock_Divider || ORIG_REF_NAME==Master_Clock_Divider}]

# XDC: ip/SD_Out_FIFO/SD_Out_FIFO/SD_Out_FIFO.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==SD_Out_FIFO || ORIG_REF_NAME==SD_Out_FIFO}] {/U0 }]/U0 ]]

# XDC: ip/ARM_FIFO_in/ARM_FIFO_in/ARM_FIFO_in.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ARM_FIFO_in || ORIG_REF_NAME==ARM_FIFO_in}] {/U0 }]/U0 ]]

# XDC: ip/ARM_FIFO_in/ARM_FIFO_in/ARM_FIFO_in_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ARM_FIFO_in || ORIG_REF_NAME==ARM_FIFO_in}] {/U0 }]/U0 ]]

# XDC: ip/ARM_FIFO_out/ARM_FIFO_out/ARM_FIFO_out.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ARM_FIFO_out || ORIG_REF_NAME==ARM_FIFO_out}] {/U0 }]/U0 ]]

# XDC: ip/ARM_FIFO_out/ARM_FIFO_out/ARM_FIFO_out_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ARM_FIFO_out || ORIG_REF_NAME==ARM_FIFO_out}] {/U0 }]/U0 ]]

# XDC: ip/sem_0/synth/sem_0_ooc.xdc

# XDC: ip/Master_Clock_Divider/Master_Clock_Divider_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Master_Clock_Divider || ORIG_REF_NAME==Master_Clock_Divider}] {/inst }]/inst ]]

# XDC: ip/Master_Clock_Divider/Master_Clock_Divider.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Master_Clock_Divider || ORIG_REF_NAME==Master_Clock_Divider}] {/inst }]/inst ]]

# XDC: ip/Master_Clock_Divider/Master_Clock_Divider_ooc.xdc
