# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k325tffg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Chance/CFTP_Sat/CFTP_Sat.cache/wt [current_project]
set_property parent.project_path C:/Users/Chance/CFTP_Sat/CFTP_Sat.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Chance/CFTP_Sat/CFTP_Sat.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/MIPS32/MIPS_Parameters.v
set_property file_type "Verilog Header" [get_files C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/MIPS32/MIPS_Parameters.v]
read_verilog -library xil_defaultlib {
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/MIPS32/Divide.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/Cache/SD/SD_Out_FIFO_Wrapper.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/Cache/SD/SD_In_ShiftRegister.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/Cache/SD/SD_Clock_Gen.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/Cache/L1/Distributed_RAM.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/Cache/Common/Counter.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/Voters/Voter.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/MIPS32/TrapDetect.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/MIPS32/RegisterFile.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/MIPS32/Register.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/MIPS32/Mux4.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/MIPS32/Mux2.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/MIPS32/MEMWB_Stage.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/MIPS32/MemControl.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/MIPS32/IFID_Stage.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/MIPS32/IDEX_Stage.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/MIPS32/Hazard_Detection.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/MIPS32/EXMEM_Stage.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/MIPS32/CPZero.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/MIPS32/Control.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/MIPS32/Compare.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/MIPS32/ALU.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/MIPS32/Add.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/Cache/SD/SD_Control.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/Cache/SD/SD_Card_Interface.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/Cache/L1/Valid_Ram.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/Cache/L1/Tag_Ram.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/Cache/L1/Hit_Detection.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/Cache/L1/Dirty_Ram.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/Cache/L1/Data_Ram.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/Cache/L1/Cache_Control.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/Voters/Processor_Voter.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/Voters/Output_Voter.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/MIPS32/Processor.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/Cache/SD/SD_Module_Interface.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/Cache/L1/Level_1_Cache.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/Cache/Bus_Arbiter/Bus_Arbiter.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/Scrubber/Configuration_Scrubber.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/PC-104_Interface/NPSAT1_ARM_CFTP_Interface.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/MIPS32/ITMR_Processor.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/Cache/L1/System_Memory.v
  C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/imports/Sources-On_Sat/Top.v
}
read_ip -quiet C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/ip/SD_Out_FIFO/SD_Out_FIFO.xci
set_property used_in_implementation false [get_files -all c:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/ip/SD_Out_FIFO/SD_Out_FIFO/SD_Out_FIFO.xdc]
set_property is_locked true [get_files C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/ip/SD_Out_FIFO/SD_Out_FIFO.xci]

read_ip -quiet C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/ip/Signed_Mult/Signed_Mult.xci
set_property is_locked true [get_files C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/ip/Signed_Mult/Signed_Mult.xci]

read_ip -quiet C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/ip/Unsigned_Mult/Unsigned_Mult.xci
set_property is_locked true [get_files C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/ip/Unsigned_Mult/Unsigned_Mult.xci]

read_ip -quiet C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/ip/ARM_FIFO_in/ARM_FIFO_in.xci
set_property used_in_implementation false [get_files -all c:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/ip/ARM_FIFO_in/ARM_FIFO_in/ARM_FIFO_in.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/ip/ARM_FIFO_in/ARM_FIFO_in/ARM_FIFO_in_clocks.xdc]
set_property is_locked true [get_files C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/ip/ARM_FIFO_in/ARM_FIFO_in.xci]

read_ip -quiet C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/ip/ARM_FIFO_out/ARM_FIFO_out.xci
set_property used_in_implementation false [get_files -all c:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/ip/ARM_FIFO_out/ARM_FIFO_out/ARM_FIFO_out.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/ip/ARM_FIFO_out/ARM_FIFO_out/ARM_FIFO_out_clocks.xdc]
set_property is_locked true [get_files C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/ip/ARM_FIFO_out/ARM_FIFO_out.xci]

read_ip -quiet C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/ip/sem_0/sem_0.xci
set_property used_in_implementation false [get_files -all c:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/ip/sem_0/synth/sem_0_ooc.xdc]
set_property is_locked true [get_files C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/ip/sem_0/sem_0.xci]

read_ip -quiet C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/ip/Master_Clock_Divider/Master_Clock_Divider.xci
set_property used_in_implementation false [get_files -all c:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/ip/Master_Clock_Divider/Master_Clock_Divider_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/ip/Master_Clock_Divider/Master_Clock_Divider.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/ip/Master_Clock_Divider/Master_Clock_Divider_ooc.xdc]
set_property is_locked true [get_files C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/sources_1/ip/Master_Clock_Divider/Master_Clock_Divider.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/constrs_1/imports/Desktop/Sources-On_Sat/mercury_kx1_top.xdc
set_property used_in_implementation false [get_files C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/constrs_1/imports/Desktop/Sources-On_Sat/mercury_kx1_top.xdc]

read_xdc C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/constrs_1/imports/Desktop/Sources/Constraints/timing.xdc
set_property used_in_implementation false [get_files C:/Users/Chance/CFTP_Sat/CFTP_Sat.srcs/constrs_1/imports/Desktop/Sources/Constraints/timing.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Top -part xc7k325tffg676-2


write_checkpoint -force -noxdef Top.dcp

catch { report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb }
