# -------------------------------------------------------------------------------------------------
# -- Project             : Mercury KX1
# -- File description    : User Constraint File
# -- File name           : mercury_kx1.xdc
# -- Authors             : Christoph Glattfelder
# -------------------------------------------------------------------------------------------------
# -- Copyright © 2013 by Enclustra GmbH, Switzerland. All rights are reserved.
# -- Unauthorized duplication of this document, in whole or in part, by any means is prohibited
# -- without the prior written permission of Enclustra GmbH, Switzerland.
# --
# -- Although Enclustra GmbH believes that the information included in this publication is correct
# -- as of the date of publication, Enclustra GmbH reserves the right to make changes at any time
# -- without notice.
# --
# -- All information in this document may only be published by Enclustra GmbH, Switzerland.
# -------------------------------------------------------------------------------------------------
# -- Notes:
# -- 1. For best I/O timing, it is necessary to set the following options in Xilinx ISE/PlanAhead:
# --    map option "Pack I/O registers into IOBs" to "Inputs and Outputs"
# -- 2. The IO standards for user banks assumes that VCC_IO* power inputs are at 3.3 V.
# -------------------------------------------------------------------------------------------------
# -- File history:
# --
# -- Version | Date       | Author             | Remarks
# -- ----------------------------------------------------------------------------------------------
# -- 1.0     | 24.02.14   | C. Glattfelder     | Converted from UCF
# --
# -------------------------------------------------------------------------------------------------

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

# -------------------------------------------------------------------------------------------------
# global clock inputs
# -------------------------------------------------------------------------------------------------

set_property IOSTANDARD LVDS [get_ports clock_200MHz_n]
set_property DIFF_TERM FALSE [get_ports clock_200MHz_n]

set_property PACKAGE_PIN AC18 [get_ports clock_200MHz_p]
set_property IOSTANDARD LVDS [get_ports clock_200MHz_p]
set_property DIFF_TERM FALSE [get_ports clock_200MHz_p]

#set_property PACKAGE_PIN AA3 [get_ports Clk100]
#set_property IOSTANDARD LVCMOS15 [get_ports Clk100]

#set_property PACKAGE_PIN B26 [get_ports Fpga_EmCclk]
#set_property IOSTANDARD LVCMOS33 [get_ports Fpga_EmCclk]

# -------------------------------------------------------------------------------------------------
# ddr3 sdram device a
# -------------------------------------------------------------------------------------------------

# Add VCCAUX_IO HIGH (FFG676 package) or VCCAUX_IO = NORMAL (FBG676 package) to all Ddr3A* nets.

#set_property IOSTANDARD DIFF_SSTL15 [get_ports Ddr3A_Clk_N]
#set_property IOSTANDARD DIFF_SSTL15 [get_ports Ddr3A_Clk_P]
#set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports Ddr3A_Dqs_N]
#set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports Ddr3A_Dqs_P]
#set_property IOSTANDARD LVCMOS15 [get_ports Ddr3A_Reset_N]
#set_property IOSTANDARD SSTL15 [get_ports Ddr3A_Cas_N]
#set_property IOSTANDARD SSTL15 [get_ports Ddr3A_Cke]
#set_property IOSTANDARD SSTL15 [get_ports Ddr3A_Cs_N]
#set_property IOSTANDARD SSTL15 [get_ports Ddr3A_Dm]
#set_property IOSTANDARD SSTL15 [get_ports Ddr3A_Odt]
#set_property IOSTANDARD SSTL15 [get_ports Ddr3A_Ras_N]
#set_property IOSTANDARD SSTL15 [get_ports Ddr3A_We_N]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3A_A[0]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3A_A[10]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3A_A[11]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3A_A[12]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3A_A[13]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3A_A[14]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3A_A[15]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3A_A[1]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3A_A[2]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3A_A[3]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3A_A[4]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3A_A[5]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3A_A[6]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3A_A[7]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3A_A[8]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3A_A[9]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3A_Ba[0]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3A_Ba[1]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3A_Ba[2]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3A_Dq[0]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3A_Dq[1]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3A_Dq[2]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3A_Dq[3]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3A_Dq[4]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3A_Dq[5]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3A_Dq[6]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3A_Dq[7]}]
#set_property PACKAGE_PIN AA4 [get_ports Ddr3A_Clk_P]
#set_property PACKAGE_PIN AA5 [get_ports {Ddr3A_Ba[0]}]
#set_property PACKAGE_PIN AB1 [get_ports {Ddr3A_A[10]}]
#set_property PACKAGE_PIN AB2 [get_ports {Ddr3A_A[14]}]
#set_property PACKAGE_PIN AB5 [get_ports {Ddr3A_Ba[1]}]
#set_property PACKAGE_PIN AB6 [get_ports {Ddr3A_Ba[2]}]
#set_property PACKAGE_PIN AC1 [get_ports {Ddr3A_A[11]}]
#set_property PACKAGE_PIN AC2 [get_ports {Ddr3A_A[15]}]
#set_property PACKAGE_PIN AC3 [get_ports Ddr3A_Cs_N]
#set_property PACKAGE_PIN AC4 [get_ports Ddr3A_Reset_N]
#set_property PACKAGE_PIN AC6 [get_ports Ddr3A_Ras_N]
#set_property PACKAGE_PIN AD1 [get_ports {Ddr3A_Dq[0]}]
#set_property PACKAGE_PIN AD4 [get_ports Ddr3A_Dm]
#set_property PACKAGE_PIN AD5 [get_ports Ddr3A_Cke]
#set_property PACKAGE_PIN AD6 [get_ports Ddr3A_Odt]
#set_property PACKAGE_PIN AE1 [get_ports {Ddr3A_Dq[1]}]
#set_property PACKAGE_PIN AE2 [get_ports {Ddr3A_Dq[3]}]
#set_property PACKAGE_PIN AE3 [get_ports {Ddr3A_Dq[2]}]
#set_property PACKAGE_PIN AE5 [get_ports {Ddr3A_Dq[5]}]
#set_property PACKAGE_PIN AE6 [get_ports {Ddr3A_Dq[4]}]
#set_property PACKAGE_PIN AF2 [get_ports {Ddr3A_Dq[7]}]
#set_property PACKAGE_PIN AF3 [get_ports {Ddr3A_Dq[6]}]
#set_property PACKAGE_PIN AF5 [get_ports Ddr3A_Dqs_P]
#set_property PACKAGE_PIN U7 [get_ports {Ddr3A_A[3]}]
#set_property PACKAGE_PIN V1 [get_ports {Ddr3A_A[9]}]
#set_property PACKAGE_PIN V2 [get_ports {Ddr3A_A[8]}]
#set_property PACKAGE_PIN V3 [get_ports {Ddr3A_A[1]}]
#set_property PACKAGE_PIN V4 [get_ports {Ddr3A_A[5]}]
#set_property PACKAGE_PIN V6 [get_ports {Ddr3A_A[4]}]
#set_property PACKAGE_PIN W1 [get_ports {Ddr3A_A[12]}]
#set_property PACKAGE_PIN W3 [get_ports {Ddr3A_A[2]}]
#set_property PACKAGE_PIN W5 [get_ports {Ddr3A_A[0]}]
#set_property PACKAGE_PIN Y1 [get_ports {Ddr3A_A[13]}]
#set_property PACKAGE_PIN Y2 [get_ports {Ddr3A_A[7]}]
#set_property PACKAGE_PIN Y3 [get_ports {Ddr3A_A[6]}]
#set_property PACKAGE_PIN Y5 [get_ports Ddr3A_We_N]
#set_property PACKAGE_PIN Y6 [get_ports Ddr3A_Cas_N]
#set_property VCCAUX_IO HIGH [get_ports Ddr3A_Clk_P]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3A_Ba[0]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3A_A[10]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3A_A[14]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3A_Ba[1]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3A_Ba[2]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3A_A[11]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3A_A[15]}]
#set_property VCCAUX_IO HIGH [get_ports Ddr3A_Cs_N]
#set_property VCCAUX_IO HIGH [get_ports Ddr3A_Reset_N]
#set_property VCCAUX_IO HIGH [get_ports Ddr3A_Ras_N]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3A_Dq[0]}]
#set_property VCCAUX_IO HIGH [get_ports Ddr3A_Dm]
#set_property VCCAUX_IO HIGH [get_ports Ddr3A_Cke]
#set_property VCCAUX_IO HIGH [get_ports Ddr3A_Odt]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3A_Dq[1]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3A_Dq[3]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3A_Dq[2]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3A_Dq[5]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3A_Dq[4]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3A_Dq[7]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3A_Dq[6]}]
#set_property VCCAUX_IO HIGH [get_ports Ddr3A_Dqs_P]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3A_A[3]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3A_A[9]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3A_A[8]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3A_A[1]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3A_A[5]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3A_A[4]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3A_A[12]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3A_A[2]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3A_A[0]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3A_A[13]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3A_A[7]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3A_A[6]}]
#set_property VCCAUX_IO HIGH [get_ports Ddr3A_We_N]
#set_property VCCAUX_IO HIGH [get_ports Ddr3A_Cas_N]

# -------------------------------------------------------------------------------------------------
# ddr3 sdram device b
# -------------------------------------------------------------------------------------------------

#set_property DCI_CASCADE {33} [get_iobanks 34]
## Add VCCAUX_IO HIGH (FFG676 package) or VCCAUX_IO = NORMAL (FBG676 package) to all Ddr3B* nets.

#set_property IOSTANDARD DIFF_SSTL15 [get_ports Ddr3B_Clk_N]
#set_property IOSTANDARD DIFF_SSTL15 [get_ports Ddr3B_Clk_P]
#set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {Ddr3B_Dqs_N[0]}]
#set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {Ddr3B_Dqs_N[1]}]
#set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {Ddr3B_Dqs_N[2]}]
#set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {Ddr3B_Dqs_N[3]}]
#set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {Ddr3B_Dqs_P[0]}]
#set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {Ddr3B_Dqs_P[1]}]
#set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {Ddr3B_Dqs_P[2]}]
#set_property IOSTANDARD DIFF_SSTL15_T_DCI [get_ports {Ddr3B_Dqs_P[3]}]
#set_property IOSTANDARD SSTL15 [get_ports Ddr3B_Cas_N]
#set_property IOSTANDARD SSTL15 [get_ports Ddr3B_Cke]
#set_property IOSTANDARD SSTL15 [get_ports Ddr3B_Cs_N]
#set_property IOSTANDARD SSTL15 [get_ports Ddr3B_Odt]
#set_property IOSTANDARD SSTL15 [get_ports Ddr3B_Ras_N]
#set_property IOSTANDARD SSTL15 [get_ports Ddr3B_Reset_N]
#set_property IOSTANDARD SSTL15 [get_ports Ddr3B_We_N]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3B_A[0]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3B_A[10]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3B_A[11]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3B_A[12]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3B_A[13]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3B_A[14]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3B_A[15]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3B_A[1]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3B_A[2]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3B_A[3]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3B_A[4]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3B_A[5]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3B_A[6]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3B_A[7]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3B_A[8]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3B_A[9]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3B_Ba[0]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3B_Ba[1]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3B_Ba[2]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3B_Dm[0]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3B_Dm[1]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3B_Dm[2]}]
#set_property IOSTANDARD SSTL15 [get_ports {Ddr3B_Dm[3]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[0]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[10]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[11]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[12]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[13]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[14]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[15]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[16]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[17]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[18]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[19]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[1]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[20]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[21]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[22]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[23]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[24]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[25]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[26]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[27]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[28]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[29]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[2]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[30]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[31]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[3]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[4]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[5]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[6]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[7]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[8]}]
#set_property IOSTANDARD SSTL15_T_DCI [get_ports {Ddr3B_Dq[9]}]
#set_property PACKAGE_PIN AA10 [get_ports {Ddr3B_Dq[18]}]
#set_property PACKAGE_PIN AA12 [get_ports {Ddr3B_Dq[21]}]
#set_property PACKAGE_PIN AA13 [get_ports {Ddr3B_Dq[20]}]
#set_property PACKAGE_PIN AA17 [get_ports {Ddr3B_Ba[2]}]
#set_property PACKAGE_PIN AA18 [get_ports Ddr3B_Ras_N]
#set_property PACKAGE_PIN AA19 [get_ports {Ddr3B_A[0]}]
#set_property PACKAGE_PIN AA20 [get_ports {Ddr3B_A[1]}]
#set_property PACKAGE_PIN AA7 [get_ports {Ddr3B_Dq[11]}]
#set_property PACKAGE_PIN AA8 [get_ports {Ddr3B_Dq[10]}]
#set_property PACKAGE_PIN AA9 [get_ports {Ddr3B_Dq[14]}]
#set_property PACKAGE_PIN AB10 [get_ports {Ddr3B_Dq[19]}]
#set_property PACKAGE_PIN AB11 [get_ports {Ddr3B_Dq[16]}]
#set_property PACKAGE_PIN AB12 [get_ports {Ddr3B_Dqs_P[2]}]
#set_property PACKAGE_PIN AB14 [get_ports {Ddr3B_Ba[0]}]
#set_property PACKAGE_PIN AB15 [get_ports {Ddr3B_Ba[1]}]
#set_property PACKAGE_PIN AB16 [get_ports Ddr3B_Cas_N]
#set_property PACKAGE_PIN AB17 [get_ports Ddr3B_Odt]
#set_property PACKAGE_PIN AB19 [get_ports {Ddr3B_A[4]}]
#set_property PACKAGE_PIN AB20 [get_ports {Ddr3B_A[5]}]
#set_property PACKAGE_PIN AB7 [get_ports {Ddr3B_Dq[12]}]
#set_property PACKAGE_PIN AB9 [get_ports {Ddr3B_Dq[15]}]
#set_property PACKAGE_PIN AC11 [get_ports {Ddr3B_Dq[17]}]
#set_property PACKAGE_PIN AC13 [get_ports {Ddr3B_Dq[22]}]
#set_property PACKAGE_PIN AC16 [get_ports Ddr3B_We_N]
#set_property PACKAGE_PIN AC17 [get_ports Ddr3B_Cke]
#set_property PACKAGE_PIN AC19 [get_ports {Ddr3B_A[2]}]
#set_property PACKAGE_PIN AC7 [get_ports {Ddr3B_Dq[13]}]
#set_property PACKAGE_PIN AC8 [get_ports {Ddr3B_Dqs_P[1]}]
#set_property PACKAGE_PIN AC9 [get_ports {Ddr3B_Dm[1]}]
#set_property PACKAGE_PIN AD10 [get_ports {Ddr3B_Dq[24]}]
#set_property PACKAGE_PIN AD11 [get_ports {Ddr3B_Dm[3]}]
#set_property PACKAGE_PIN AD13 [get_ports {Ddr3B_Dq[23]}]
#set_property PACKAGE_PIN AD19 [get_ports {Ddr3B_A[3]}]
#set_property PACKAGE_PIN AD20 [get_ports Ddr3B_Clk_P]
#set_property PACKAGE_PIN AE10 [get_ports {Ddr3B_Dq[25]}]
#set_property PACKAGE_PIN AE12 [get_ports {Ddr3B_Dqs_P[3]}]
#set_property PACKAGE_PIN AE13 [get_ports {Ddr3B_Dq[28]}]
#set_property PACKAGE_PIN AE7 [get_ports {Ddr3B_Dq[8]}]
#set_property PACKAGE_PIN AE8 [get_ports {Ddr3B_Dq[26]}]
#set_property PACKAGE_PIN AF10 [get_ports {Ddr3B_Dq[30]}]
#set_property PACKAGE_PIN AF13 [get_ports {Ddr3B_Dq[29]}]
#set_property PACKAGE_PIN AF7 [get_ports {Ddr3B_Dq[9]}]
#set_property PACKAGE_PIN AF8 [get_ports {Ddr3B_Dq[27]}]
#set_property PACKAGE_PIN AF9 [get_ports {Ddr3B_Dq[31]}]
#set_property PACKAGE_PIN V11 [get_ports {Ddr3B_Dq[0]}]
#set_property PACKAGE_PIN V14 [get_ports {Ddr3B_A[15]}]
#set_property PACKAGE_PIN V16 [get_ports {Ddr3B_A[7]}]
#set_property PACKAGE_PIN V17 [get_ports {Ddr3B_A[8]}]
#set_property PACKAGE_PIN V18 [get_ports {Ddr3B_A[13]}]
#set_property PACKAGE_PIN V19 [get_ports {Ddr3B_A[14]}]
#set_property PACKAGE_PIN V7 [get_ports {Ddr3B_Dq[3]}]
#set_property PACKAGE_PIN V8 [get_ports {Ddr3B_Dq[2]}]
#set_property PACKAGE_PIN V9 [get_ports {Ddr3B_Dm[0]}]
#set_property PACKAGE_PIN W10 [get_ports {Ddr3B_Dqs_P[0]}]
#set_property PACKAGE_PIN W11 [get_ports {Ddr3B_Dq[1]}]
#set_property PACKAGE_PIN W15 [get_ports {Ddr3B_A[11]}]
#set_property PACKAGE_PIN W16 [get_ports {Ddr3B_A[12]}]
#set_property PACKAGE_PIN W18 [get_ports {Ddr3B_A[9]}]
#set_property PACKAGE_PIN W19 [get_ports {Ddr3B_A[10]}]
#set_property PACKAGE_PIN Y10 [get_ports {Ddr3B_Dq[7]}]
#set_property PACKAGE_PIN Y11 [get_ports {Ddr3B_Dq[6]}]
#set_property PACKAGE_PIN Y13 [get_ports {Ddr3B_Dm[2]}]
#set_property PACKAGE_PIN Y15 [get_ports Ddr3B_Reset_N]
#set_property PACKAGE_PIN Y16 [get_ports Ddr3B_Cs_N]
#set_property PACKAGE_PIN Y17 [get_ports {Ddr3B_A[6]}]
#set_property PACKAGE_PIN Y7 [get_ports {Ddr3B_Dq[5]}]
#set_property PACKAGE_PIN Y8 [get_ports {Ddr3B_Dq[4]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[18]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[21]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[20]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Ba[2]}]
#set_property VCCAUX_IO HIGH [get_ports Ddr3B_Ras_N]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_A[0]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_A[1]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[11]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[10]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[14]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[19]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[16]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dqs_P[2]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Ba[0]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Ba[1]}]
#set_property VCCAUX_IO HIGH [get_ports Ddr3B_Cas_N]
#set_property VCCAUX_IO HIGH [get_ports Ddr3B_Odt]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_A[4]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_A[5]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[12]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[15]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[17]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[22]}]
#set_property VCCAUX_IO HIGH [get_ports Ddr3B_We_N]
#set_property VCCAUX_IO HIGH [get_ports Ddr3B_Cke]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_A[2]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[13]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dqs_P[1]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dm[1]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[24]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dm[3]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[23]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_A[3]}]
#set_property VCCAUX_IO HIGH [get_ports Ddr3B_Clk_P]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[25]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dqs_P[3]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[28]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[8]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[26]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[30]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[29]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[9]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[27]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[31]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[0]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_A[15]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_A[7]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_A[8]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_A[13]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_A[14]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[3]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[2]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dm[0]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dqs_P[0]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[1]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_A[11]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_A[12]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_A[9]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_A[10]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[7]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[6]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dm[2]}]
#set_property VCCAUX_IO HIGH [get_ports Ddr3B_Reset_N]
#set_property VCCAUX_IO HIGH [get_ports Ddr3B_Cs_N]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_A[6]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[5]}]
#set_property VCCAUX_IO HIGH [get_ports {Ddr3B_Dq[4]}]

## -------------------------------------------------------------------------------------------------
## ethernet
## -------------------------------------------------------------------------------------------------

#set_property IOSTANDARD LVCMOS15 [get_ports Eth_Int_N]
#set_property IOSTANDARD LVCMOS33 [get_ports Eth_Mdc]
#set_property IOSTANDARD LVCMOS33 [get_ports Eth_Mdio]
#set_property IOSTANDARD LVCMOS33 [get_ports Eth_Reset_N]
#set_property PACKAGE_PIN M20 [get_ports Eth_Reset_N]
#set_property PACKAGE_PIN N16 [get_ports Eth_Mdc]
#set_property PACKAGE_PIN U16 [get_ports Eth_Mdio]
#set_property PACKAGE_PIN V12 [get_ports Eth_Int_N]
#set_property SLEW SLOW [get_ports Eth_Mdc]
#set_property SLEW SLOW [get_ports Eth_Mdio]
#set_property SLEW SLOW [get_ports Eth_Reset_N]


#set_property IOSTANDARD LVCMOS33 [get_ports Eth0_Led2_N]
#set_property IOSTANDARD LVCMOS33 [get_ports Eth0_Rx_Clk]
#set_property IOSTANDARD LVCMOS33 [get_ports Eth0_Rx_Ctl]
#set_property IOSTANDARD LVCMOS33 [get_ports Eth0_Tx_Clk]
#set_property IOSTANDARD LVCMOS33 [get_ports Eth0_Tx_Ctl]
#set_property IOSTANDARD LVCMOS33 [get_ports {Eth0_Rxd[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Eth0_Rxd[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Eth0_Rxd[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Eth0_Rxd[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Eth0_Txd[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Eth0_Txd[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Eth0_Txd[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Eth0_Txd[3]}]
#set_property PACKAGE_PIN M16 [get_ports Eth0_Led2_N]
#set_property PACKAGE_PIN M19 [get_ports {Eth0_Txd[1]}]
#set_property PACKAGE_PIN N17 [get_ports {Eth0_Rxd[1]}]
#set_property PACKAGE_PIN N18 [get_ports {Eth0_Txd[0]}]
#set_property PACKAGE_PIN P16 [get_ports {Eth0_Rxd[0]}]
#set_property PACKAGE_PIN P18 [get_ports Eth0_Tx_Ctl]
#set_property PACKAGE_PIN P21 [get_ports Eth0_Rx_Ctl]
#set_property PACKAGE_PIN R16 [get_ports {Eth0_Rxd[2]}]
#set_property PACKAGE_PIN R17 [get_ports {Eth0_Rxd[3]}]
#set_property PACKAGE_PIN R18 [get_ports Eth0_Tx_Clk]
#set_property PACKAGE_PIN R21 [get_ports Eth0_Rx_Clk]
#set_property PACKAGE_PIN T17 [get_ports {Eth0_Txd[3]}]
#set_property PACKAGE_PIN U17 [get_ports {Eth0_Txd[2]}]
#set_property SLEW FAST [get_ports Eth0_Tx_Clk]
#set_property SLEW FAST [get_ports Eth0_Tx_Ctl]
#set_property SLEW FAST [get_ports {Eth0_Txd[0]}]
#set_property SLEW FAST [get_ports {Eth0_Txd[1]}]
#set_property SLEW FAST [get_ports {Eth0_Txd[2]}]
#set_property SLEW FAST [get_ports {Eth0_Txd[3]}]

#set_property IOSTANDARD LVCMOS33 [get_ports Eth1_Led2_N]
#set_property IOSTANDARD LVCMOS33 [get_ports Eth1_Rx_Clk]
#set_property IOSTANDARD LVCMOS33 [get_ports Eth1_Rx_Ctl]
#set_property IOSTANDARD LVCMOS33 [get_ports Eth1_Tx_Clk]
#set_property IOSTANDARD LVCMOS33 [get_ports Eth1_Tx_Ctl]
#set_property IOSTANDARD LVCMOS33 [get_ports {Eth1_Rxd[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Eth1_Rxd[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Eth1_Rxd[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Eth1_Rxd[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Eth1_Txd[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Eth1_Txd[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Eth1_Txd[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Eth1_Txd[3]}]
#set_property PACKAGE_PIN K15 [get_ports Eth1_Led2_N]
#set_property PACKAGE_PIN M21 [get_ports Eth1_Tx_Clk]
#set_property PACKAGE_PIN M22 [get_ports Eth1_Tx_Ctl]
#set_property PACKAGE_PIN R20 [get_ports {Eth1_Rxd[1]}]
#set_property PACKAGE_PIN R22 [get_ports Eth1_Rx_Clk]
#set_property PACKAGE_PIN R23 [get_ports Eth1_Rx_Ctl]
#set_property PACKAGE_PIN T18 [get_ports {Eth1_Txd[2]}]
#set_property PACKAGE_PIN T19 [get_ports {Eth1_Txd[3]}]
#set_property PACKAGE_PIN T20 [get_ports {Eth1_Rxd[0]}]
#set_property PACKAGE_PIN T22 [get_ports {Eth1_Rxd[2]}]
#set_property PACKAGE_PIN T23 [get_ports {Eth1_Rxd[3]}]
#set_property PACKAGE_PIN U19 [get_ports {Eth1_Txd[0]}]
#set_property PACKAGE_PIN U20 [get_ports {Eth1_Txd[1]}]
#set_property SLEW FAST [get_ports Eth1_Tx_Clk]
#set_property SLEW FAST [get_ports Eth1_Tx_Ctl]
#set_property SLEW FAST [get_ports {Eth1_Txd[0]}]
#set_property SLEW FAST [get_ports {Eth1_Txd[1]}]
#set_property SLEW FAST [get_ports {Eth1_Txd[2]}]
#set_property SLEW FAST [get_ports {Eth1_Txd[3]}]

## -------------------------------------------------------------------------------------------------
## spi flash
## -------------------------------------------------------------------------------------------------

#set_property IOSTANDARD LVCMOS33 [get_ports Flash_Clk]
#set_property IOSTANDARD LVCMOS33 [get_ports Flash_Cs_N]
#set_property IOSTANDARD LVCMOS33 [get_ports Flash_Di]
#set_property IOSTANDARD LVCMOS33 [get_ports Flash_Do]
#set_property IOSTANDARD LVCMOS33 [get_ports Flash_Hold_N]
#set_property IOSTANDARD LVCMOS33 [get_ports Flash_Wp_N]
#set_property PACKAGE_PIN A22 [get_ports Flash_Hold_N]
#set_property PACKAGE_PIN A25 [get_ports Flash_Do]
#set_property PACKAGE_PIN B22 [get_ports Flash_Wp_N]
#set_property PACKAGE_PIN B24 [get_ports Flash_Di]
#set_property PACKAGE_PIN C23 [get_ports Flash_Cs_N]
#set_property PACKAGE_PIN K21 [get_ports Flash_Clk]
#set_property SLEW FAST [get_ports Flash_Clk]
#set_property SLEW FAST [get_ports Flash_Cs_N]
#set_property SLEW FAST [get_ports Flash_Di]
#set_property SLEW FAST [get_ports Flash_Do]
#set_property SLEW FAST [get_ports Flash_Hold_N]
#set_property SLEW FAST [get_ports Flash_Wp_N]

## -------------------------------------------------------------------------------------------------
## ez-usb fx3
## -------------------------------------------------------------------------------------------------

#set_property IOSTANDARD LVCMOS33 [get_ports Fx3_Clk]
#set_property IOSTANDARD LVCMOS33 [get_ports Fx3_Flaga]
#set_property IOSTANDARD LVCMOS33 [get_ports Fx3_Flagb]
#set_property IOSTANDARD LVCMOS33 [get_ports Fx3_Int_N]
#set_property IOSTANDARD LVCMOS33 [get_ports Fx3_Pktend_N]
#set_property IOSTANDARD LVCMOS33 [get_ports Fx3_Reset_N]
#set_property IOSTANDARD LVCMOS33 [get_ports Fx3_Slcs_N]
#set_property IOSTANDARD LVCMOS33 [get_ports Fx3_Sloe_N]
#set_property IOSTANDARD LVCMOS33 [get_ports Fx3_Slrd_N]
#set_property IOSTANDARD LVCMOS33 [get_ports Fx3_Slwr_N]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Ad[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Ad[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[10]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[11]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[12]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[13]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[14]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[15]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[16]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[17]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[18]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[19]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[20]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[21]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[22]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[23]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[24]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[25]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[26]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[27]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[28]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[29]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[30]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[31]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[8]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Fx3_Dq[9]}]
#set_property KEEPER true [get_ports {Fx3_Dq[0]}]
#set_property KEEPER true [get_ports {Fx3_Dq[10]}]
#set_property KEEPER true [get_ports {Fx3_Dq[11]}]
#set_property KEEPER true [get_ports {Fx3_Dq[12]}]
#set_property KEEPER true [get_ports {Fx3_Dq[13]}]
#set_property KEEPER true [get_ports {Fx3_Dq[14]}]
#set_property KEEPER true [get_ports {Fx3_Dq[15]}]
#set_property KEEPER true [get_ports {Fx3_Dq[16]}]
#set_property KEEPER true [get_ports {Fx3_Dq[17]}]
#set_property KEEPER true [get_ports {Fx3_Dq[18]}]
#set_property KEEPER true [get_ports {Fx3_Dq[19]}]
#set_property KEEPER true [get_ports {Fx3_Dq[1]}]
#set_property KEEPER true [get_ports {Fx3_Dq[20]}]
#set_property KEEPER true [get_ports {Fx3_Dq[21]}]
#set_property KEEPER true [get_ports {Fx3_Dq[22]}]
#set_property KEEPER true [get_ports {Fx3_Dq[23]}]
#set_property KEEPER true [get_ports {Fx3_Dq[24]}]
#set_property KEEPER true [get_ports {Fx3_Dq[25]}]
#set_property KEEPER true [get_ports {Fx3_Dq[26]}]
#set_property KEEPER true [get_ports {Fx3_Dq[27]}]
#set_property KEEPER true [get_ports {Fx3_Dq[28]}]
#set_property KEEPER true [get_ports {Fx3_Dq[29]}]
#set_property KEEPER true [get_ports {Fx3_Dq[2]}]
#set_property KEEPER true [get_ports {Fx3_Dq[30]}]
#set_property KEEPER true [get_ports {Fx3_Dq[31]}]
#set_property KEEPER true [get_ports {Fx3_Dq[3]}]
#set_property KEEPER true [get_ports {Fx3_Dq[4]}]
#set_property KEEPER true [get_ports {Fx3_Dq[5]}]
#set_property KEEPER true [get_ports {Fx3_Dq[6]}]
#set_property KEEPER true [get_ports {Fx3_Dq[7]}]
#set_property KEEPER true [get_ports {Fx3_Dq[8]}]
#set_property KEEPER true [get_ports {Fx3_Dq[9]}]
#set_property PACKAGE_PIN A20 [get_ports {Fx3_Dq[7]}]
#set_property PACKAGE_PIN A23 [get_ports {Fx3_Dq[0]}]
#set_property PACKAGE_PIN A24 [get_ports {Fx3_Dq[1]}]
#set_property PACKAGE_PIN B20 [get_ports {Fx3_Dq[6]}]
#set_property PACKAGE_PIN B21 [get_ports {Fx3_Dq[11]}]
#set_property PACKAGE_PIN C21 [get_ports {Fx3_Dq[10]}]
#set_property PACKAGE_PIN C22 [get_ports {Fx3_Dq[5]}]
#set_property PACKAGE_PIN C24 [get_ports Fx3_Sloe_N]
#set_property PACKAGE_PIN C26 [get_ports {Fx3_Dq[3]}]
#set_property PACKAGE_PIN D21 [get_ports {Fx3_Dq[4]}]
#set_property PACKAGE_PIN D23 [get_ports {Fx3_Dq[12]}]
#set_property PACKAGE_PIN D24 [get_ports {Fx3_Dq[13]}]
#set_property PACKAGE_PIN D25 [get_ports {Fx3_Dq[19]}]
#set_property PACKAGE_PIN D26 [get_ports {Fx3_Dq[2]}]
#set_property PACKAGE_PIN E21 [get_ports {Fx3_Dq[8]}]
#set_property PACKAGE_PIN E22 [get_ports {Fx3_Dq[9]}]
#set_property PACKAGE_PIN E23 [get_ports {Fx3_Dq[15]}]
#set_property PACKAGE_PIN E25 [get_ports {Fx3_Dq[18]}]
#set_property PACKAGE_PIN E26 [get_ports {Fx3_Dq[23]}]
#set_property PACKAGE_PIN F22 [get_ports {Fx3_Dq[14]}]
#set_property PACKAGE_PIN F23 [get_ports Fx3_Pktend_N]
#set_property PACKAGE_PIN F24 [get_ports {Fx3_Dq[17]}]
#set_property PACKAGE_PIN F25 [get_ports {Fx3_Dq[22]}]
#set_property PACKAGE_PIN G21 [get_ports {Fx3_Dq[27]}]
#set_property PACKAGE_PIN G22 [get_ports Fx3_Clk]
#set_property PACKAGE_PIN G24 [get_ports {Fx3_Dq[16]}]
#set_property PACKAGE_PIN G25 [get_ports {Fx3_Dq[20]}]
#set_property PACKAGE_PIN G26 [get_ports {Fx3_Dq[21]}]
#set_property PACKAGE_PIN H21 [get_ports {Fx3_Dq[26]}]
#set_property PACKAGE_PIN H22 [get_ports {Fx3_Dq[31]}]
#set_property PACKAGE_PIN H23 [get_ports {Fx3_Dq[28]}]
#set_property PACKAGE_PIN H24 [get_ports {Fx3_Dq[29]}]
#set_property PACKAGE_PIN H26 [get_ports {Fx3_Dq[25]}]
#set_property PACKAGE_PIN J21 [get_ports {Fx3_Dq[30]}]
#set_property PACKAGE_PIN J23 [get_ports Fx3_Flagb]
#set_property PACKAGE_PIN J24 [get_ports {Fx3_Ad[0]}]
#set_property PACKAGE_PIN J25 [get_ports {Fx3_Ad[1]}]
#set_property PACKAGE_PIN J26 [get_ports {Fx3_Dq[24]}]
#set_property PACKAGE_PIN K22 [get_ports Fx3_Slrd_N]
#set_property PACKAGE_PIN K23 [get_ports Fx3_Flaga]
#set_property PACKAGE_PIN L22 [get_ports Fx3_Slwr_N]
#set_property PACKAGE_PIN L23 [get_ports Fx3_Slcs_N]
#set_property PACKAGE_PIN P19 [get_ports Fx3_Int_N]
#set_property PACKAGE_PIN P20 [get_ports Fx3_Reset_N]
#set_property SLEW FAST [get_ports Fx3_Clk]
#set_property SLEW FAST [get_ports Fx3_Flaga]
#set_property SLEW FAST [get_ports Fx3_Flagb]
#set_property SLEW FAST [get_ports Fx3_Int_N]
#set_property SLEW FAST [get_ports Fx3_Pktend_N]
#set_property SLEW FAST [get_ports Fx3_Slcs_N]
#set_property SLEW FAST [get_ports Fx3_Sloe_N]
#set_property SLEW FAST [get_ports Fx3_Slrd_N]
#set_property SLEW FAST [get_ports Fx3_Slwr_N]
#set_property SLEW FAST [get_ports {Fx3_Ad[0]}]
#set_property SLEW FAST [get_ports {Fx3_Ad[1]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[0]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[10]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[11]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[12]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[13]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[14]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[15]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[16]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[17]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[18]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[19]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[1]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[20]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[21]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[22]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[23]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[24]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[25]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[26]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[27]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[28]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[29]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[2]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[30]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[31]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[3]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[4]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[5]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[6]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[7]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[8]}]
#set_property SLEW FAST [get_ports {Fx3_Dq[9]}]
#set_property SLEW SLOW [get_ports Fx3_Reset_N]

## -------------------------------------------------------------------------------------------------
## i2c
## -------------------------------------------------------------------------------------------------

#set_property IOSTANDARD LVCMOS33 [get_ports I2c_Int_N]
#set_property IOSTANDARD LVCMOS33 [get_ports I2c_Scl]
#set_property IOSTANDARD LVCMOS33 [get_ports I2c_Sda]
#set_property PACKAGE_PIN N19 [get_ports I2c_Int_N]
#set_property PACKAGE_PIN N24 [get_ports I2c_Scl]
#set_property PACKAGE_PIN P24 [get_ports I2c_Sda]
#set_property SLEW SLOW [get_ports I2c_Int_N]
#set_property SLEW SLOW [get_ports I2c_Scl]
#set_property SLEW SLOW [get_ports I2c_Sda]

## -------------------------------------------------------------------------------------------------
## led
## -------------------------------------------------------------------------------------------------

set_property IOSTANDARD LVCMOS33 [get_ports Heartbeat_out]
#set_property IOSTANDARD LVCMOS33 [get_ports {Led_N[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Led_N[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {Led_N[3]}]
#set_property PACKAGE_PIN K18 [get_ports {Led_N[3]}]
#set_property PACKAGE_PIN L17 [get_ports {Led_N[2]}]
#set_property PACKAGE_PIN L18 [get_ports {Led_N[1]}]
set_property PACKAGE_PIN M17 [get_ports Heartbeat_out]
set_property SLEW SLOW [get_ports Heartbeat_out]
#set_property SLEW SLOW [get_ports {Led_N[1]}]
#set_property SLEW SLOW [get_ports {Led_N[2]}]
#set_property SLEW SLOW [get_ports {Led_N[3]}]

## -------------------------------------------------------------------------------------------------
## system
## -------------------------------------------------------------------------------------------------

#set_property IOSTANDARD LVCMOS15 [get_ports Pwr_Good]
#set_property IOSTANDARD LVCMOS33 [get_ports Ddr3_Vsel]
#set_property IOSTANDARD LVCMOS33 [get_ports Fpga_Init_B]
#set_property IOSTANDARD LVCMOS33 [get_ports Fpga_Pudc_B]
#set_property PACKAGE_PIN B25 [get_ports Fpga_Pudc_B]
#set_property PACKAGE_PIN J14 [get_ports Fpga_Init_B]
#set_property PACKAGE_PIN J8 [get_ports Ddr3_Vsel]
#set_property PACKAGE_PIN U9 [get_ports Pwr_Good]
#set_property SLEW SLOW [get_ports Ddr3_Vsel]
#set_property SLEW SLOW [get_ports Fpga_Init_B]
#set_property SLEW SLOW [get_ports Fpga_Pudc_B]
#set_property SLEW SLOW [get_ports Pwr_Good]

## -------------------------------------------------------------------------------------------------
## bank 12 - module connector
## -------------------------------------------------------------------------------------------------

set_property IOSTANDARD LVCMOS33 [get_ports {ARM_Address_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_Address_in[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B12_L11N_SRCC_AB24]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B12_L11P_SRCC_AA23]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B12_L12N_MRCC_AA24]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B12_L12P_MRCC_Y23]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B12_L13N_MRCC_AA22]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B12_L13P_MRCC_Y22]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B12_L14N_SRCC_AC24]
set_property IOSTANDARD LVCMOS33 [get_ports ARM_BCLK_in]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_Data_inout[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_Data_inout[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_Address_in[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_Address_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_Data_inout[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_Data_inout[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B12_L18N_AC21]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B12_L18P_AB21]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B12_L19N_VREF_AE21]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_Data_inout[12]}]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B12_L1N_V22]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B12_L1P_U22]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_Address_in[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_Address_in[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_Data_inout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_Data_inout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_Data_inout[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_Data_inout[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_Data_inout[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_Data_inout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports ARM_Data_Direction]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_Data_inout[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports ARM_CS_in]
#set_property IOSTANDARD LVCMOS33 [get_ports Reset]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_Address_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_Address_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_Address_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_Address_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports ARM_Read_in]
set_property IOSTANDARD LVCMOS33 [get_ports ARM_Write_in]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B12_L6N_VREF_W21]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_Address_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_Data_inout[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_Data_inout[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports ARM_IRQ_out]
#set_property IOSTANDARD LVCMOS33 [get_ports Pwr_Req]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_Data_inout[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ARM_Data_inout[10]}]
#set_property PACKAGE_PIN AA22 [get_ports IO_B12_L13N_MRCC_AA22]
#set_property PACKAGE_PIN AA23 [get_ports IO_B12_L11P_SRCC_AA23]
#set_property PACKAGE_PIN AA24 [get_ports IO_B12_L12N_MRCC_AA24]
set_property PACKAGE_PIN AA25 [get_ports {ARM_Data_inout[8]}]
#set_property PACKAGE_PIN AB21 [get_ports IO_B12_L18P_AB21]
set_property PACKAGE_PIN AB22 [get_ports {ARM_Data_inout[5]}]
#set_property PACKAGE_PIN AB24 [get_ports IO_B12_L11N_SRCC_AB24]
set_property PACKAGE_PIN AB25 [get_ports {ARM_Data_inout[9]}]
set_property PACKAGE_PIN AB26 [get_ports {ARM_Data_inout[10]}]
#set_property PACKAGE_PIN AC21 [get_ports IO_B12_L18N_AC21]
set_property PACKAGE_PIN AC22 [get_ports {ARM_Data_inout[4]}]
set_property PACKAGE_PIN AC23 [get_ports ARM_BCLK_in]
#set_property PACKAGE_PIN AC24 [get_ports IO_B12_L14N_SRCC_AC24]
set_property PACKAGE_PIN AC26 [get_ports {ARM_Data_inout[11]}]
set_property PACKAGE_PIN AD21 [get_ports {ARM_Data_inout[12]}]
set_property PACKAGE_PIN AD23 [get_ports {ARM_Address_in[7]}]
set_property PACKAGE_PIN AD24 [get_ports {ARM_Address_in[8]}]
set_property PACKAGE_PIN AD25 [get_ports {ARM_Data_inout[1]}]
set_property PACKAGE_PIN AD26 [get_ports {ARM_Data_inout[3]}]
#set_property PACKAGE_PIN AE21 [get_ports IO_B12_L19N_VREF_AE21]
set_property PACKAGE_PIN AE22 [get_ports {ARM_Data_inout[15]}]
set_property PACKAGE_PIN AE23 [get_ports {ARM_Data_inout[13]}]
set_property PACKAGE_PIN AE25 [get_ports {ARM_Data_inout[0]}]
set_property PACKAGE_PIN AE26 [get_ports {ARM_Data_inout[2]}]
set_property PACKAGE_PIN AF22 [get_ports ARM_Data_Direction]
set_property PACKAGE_PIN AF23 [get_ports {ARM_Data_inout[14]}]
set_property PACKAGE_PIN AF24 [get_ports {ARM_Address_in[9]}]
set_property PACKAGE_PIN AF25 [get_ports {ARM_Address_in[10]}]
#set_property PACKAGE_PIN U22 [get_ports IO_B12_L1P_U22]
#set_property PACKAGE_PIN U24 [get_ports Reset]
set_property PACKAGE_PIN U25 [get_ports ARM_CS_in]
set_property PACKAGE_PIN U26 [get_ports {ARM_Address_in[3]}]
set_property PACKAGE_PIN V21 [get_ports {ARM_Address_in[0]}]
#set_property PACKAGE_PIN V22 [get_ports IO_B12_L1N_V22]
set_property PACKAGE_PIN V23 [get_ports {ARM_Address_in[1]}]
set_property PACKAGE_PIN V24 [get_ports {ARM_Address_in[2]}]
set_property PACKAGE_PIN V26 [get_ports {ARM_Address_in[4]}]
set_property PACKAGE_PIN W20 [get_ports {ARM_Data_inout[7]}]
#set_property PACKAGE_PIN W21 [get_ports IO_B12_L6N_VREF_W21]
#set_property PACKAGE_PIN W23 [get_ports Pwr_Req]
set_property PACKAGE_PIN W24 [get_ports ARM_IRQ_out]
set_property PACKAGE_PIN W25 [get_ports ARM_Write_in]
set_property PACKAGE_PIN W26 [get_ports ARM_Read_in]
set_property PACKAGE_PIN Y21 [get_ports {ARM_Data_inout[6]}]
#set_property PACKAGE_PIN Y22 [get_ports IO_B12_L13P_MRCC_Y22]
#set_property PACKAGE_PIN Y23 [get_ports IO_B12_L12P_MRCC_Y23]
set_property PACKAGE_PIN Y25 [get_ports {ARM_Address_in[5]}]
set_property PACKAGE_PIN Y26 [get_ports {ARM_Address_in[6]}]

## -------------------------------------------------------------------------------------------------
## bank 13 - module connector
## -------------------------------------------------------------------------------------------------

#set_property IOSTANDARD LVCMOS33 [get_ports IO_B13_L11N_SRCC_N23]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B13_L11P_SRCC_P23]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B13_L12N_MRCC_N22]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B13_L12P_MRCC_N21]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B13_L15N_T25]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B13_L15P_T24]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B13_L1N_K26]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B13_L1P_K25]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B13_L2N_P26]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B13_L2P_R26]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B13_L3N_L25]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B13_L3P_M25]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B13_L5N_M26]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B13_L5P_N26]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B13_L6N_P25]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B13_L6P_R25]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B13_L8N_L24]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B13_L8P_M24]
#set_property PACKAGE_PIN K25 [get_ports IO_B13_L1P_K25]
#set_property PACKAGE_PIN K26 [get_ports IO_B13_L1N_K26]
#set_property PACKAGE_PIN L24 [get_ports IO_B13_L8N_L24]
#set_property PACKAGE_PIN L25 [get_ports IO_B13_L3N_L25]
#set_property PACKAGE_PIN M24 [get_ports IO_B13_L8P_M24]
#set_property PACKAGE_PIN M25 [get_ports IO_B13_L3P_M25]
#set_property PACKAGE_PIN M26 [get_ports IO_B13_L5N_M26]
#set_property PACKAGE_PIN N21 [get_ports IO_B13_L12P_MRCC_N21]
#set_property PACKAGE_PIN N22 [get_ports IO_B13_L12N_MRCC_N22]
#set_property PACKAGE_PIN N23 [get_ports IO_B13_L11N_SRCC_N23]
#set_property PACKAGE_PIN N26 [get_ports IO_B13_L5P_N26]
#set_property PACKAGE_PIN P23 [get_ports IO_B13_L11P_SRCC_P23]
#set_property PACKAGE_PIN P25 [get_ports IO_B13_L6N_P25]
#set_property PACKAGE_PIN P26 [get_ports IO_B13_L2N_P26]
#set_property PACKAGE_PIN R25 [get_ports IO_B13_L6P_R25]
#set_property PACKAGE_PIN R26 [get_ports IO_B13_L2P_R26]
#set_property PACKAGE_PIN T24 [get_ports IO_B13_L15P_T24]
#set_property PACKAGE_PIN T25 [get_ports IO_B13_L15N_T25]

## -------------------------------------------------------------------------------------------------
## bank 15 - module connector
## -------------------------------------------------------------------------------------------------

#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L10N_AD4N_E16]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L10P_AD4P_E15]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L11N_SRCC_AD12N_F18]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L11P_SRCC_AD12P_G17]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L12N_MRCC_AD5N_E17]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L12P_MRCC_AD5P_F17]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L13N_MRCC_D18]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L13P_MRCC_E18]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L14N_SRCC_H18]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L14P_SRCC_H17]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L15N_D20]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L15P_D19]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L16N_A27_F20]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L16P_A28_G19]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L17N_A25_E20]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L17P_A26_F19]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L18N_A23_G20]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L18P_A24_H19]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L19N_A21_VREF_J20]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L19P_A22_K20]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L1N_AD0N_B16]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L1P_AD0P_C16]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L20N_A19_J19]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L20P_A20_J18]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L21N_A18_L20]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L21P_L19]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L22N_A16_K17]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L22P_A17_K16]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L2N_AD8N_A19]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L2P_AD8P_A18]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L3N_AD1N_A17]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L3P_AD1P_B17]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L4N_AD9N_B19]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L4P_AD9P_C19]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L5N_AD2N_C18]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L5P_AD2P_C17]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L6N_VREF_D16]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L6P_D15]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L7N_AD10N_G16]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L7P_AD10P_H16]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L8N_AD3N_F15]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L8P_AD3P_G15]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L9N_AD11N_J16]
#set_property IOSTANDARD LVCMOS33 [get_ports IO_B15_L9P_AD11P_J15]
#set_property PACKAGE_PIN A17 [get_ports IO_B15_L3N_AD1N_A17]
#set_property PACKAGE_PIN A18 [get_ports IO_B15_L2P_AD8P_A18]
#set_property PACKAGE_PIN A19 [get_ports IO_B15_L2N_AD8N_A19]
#set_property PACKAGE_PIN B16 [get_ports IO_B15_L1N_AD0N_B16]
#set_property PACKAGE_PIN B17 [get_ports IO_B15_L3P_AD1P_B17]
#set_property PACKAGE_PIN B19 [get_ports IO_B15_L4N_AD9N_B19]
#set_property PACKAGE_PIN C16 [get_ports IO_B15_L1P_AD0P_C16]
#set_property PACKAGE_PIN C17 [get_ports IO_B15_L5P_AD2P_C17]
#set_property PACKAGE_PIN C18 [get_ports IO_B15_L5N_AD2N_C18]
#set_property PACKAGE_PIN C19 [get_ports IO_B15_L4P_AD9P_C19]
#set_property PACKAGE_PIN D15 [get_ports IO_B15_L6P_D15]
#set_property PACKAGE_PIN D16 [get_ports IO_B15_L6N_VREF_D16]
#set_property PACKAGE_PIN D18 [get_ports IO_B15_L13N_MRCC_D18]
#set_property PACKAGE_PIN D19 [get_ports IO_B15_L15P_D19]
#set_property PACKAGE_PIN D20 [get_ports IO_B15_L15N_D20]
#set_property PACKAGE_PIN E15 [get_ports IO_B15_L10P_AD4P_E15]
#set_property PACKAGE_PIN E16 [get_ports IO_B15_L10N_AD4N_E16]
#set_property PACKAGE_PIN E17 [get_ports IO_B15_L12N_MRCC_AD5N_E17]
#set_property PACKAGE_PIN E18 [get_ports IO_B15_L13P_MRCC_E18]
#set_property PACKAGE_PIN E20 [get_ports IO_B15_L17N_A25_E20]
#set_property PACKAGE_PIN F15 [get_ports IO_B15_L8N_AD3N_F15]
#set_property PACKAGE_PIN F17 [get_ports IO_B15_L12P_MRCC_AD5P_F17]
#set_property PACKAGE_PIN F18 [get_ports IO_B15_L11N_SRCC_AD12N_F18]
#set_property PACKAGE_PIN F19 [get_ports IO_B15_L17P_A26_F19]
#set_property PACKAGE_PIN F20 [get_ports IO_B15_L16N_A27_F20]
#set_property PACKAGE_PIN G15 [get_ports IO_B15_L8P_AD3P_G15]
#set_property PACKAGE_PIN G16 [get_ports IO_B15_L7N_AD10N_G16]
#set_property PACKAGE_PIN G17 [get_ports IO_B15_L11P_SRCC_AD12P_G17]
#set_property PACKAGE_PIN G19 [get_ports IO_B15_L16P_A28_G19]
#set_property PACKAGE_PIN G20 [get_ports IO_B15_L18N_A23_G20]
#set_property PACKAGE_PIN H16 [get_ports IO_B15_L7P_AD10P_H16]
#set_property PACKAGE_PIN H17 [get_ports IO_B15_L14P_SRCC_H17]
#set_property PACKAGE_PIN H18 [get_ports IO_B15_L14N_SRCC_H18]
#set_property PACKAGE_PIN H19 [get_ports IO_B15_L18P_A24_H19]
#set_property PACKAGE_PIN J15 [get_ports IO_B15_L9P_AD11P_J15]
#set_property PACKAGE_PIN J16 [get_ports IO_B15_L9N_AD11N_J16]
#set_property PACKAGE_PIN J18 [get_ports IO_B15_L20P_A20_J18]
#set_property PACKAGE_PIN J19 [get_ports IO_B15_L20N_A19_J19]
#set_property PACKAGE_PIN J20 [get_ports IO_B15_L19N_A21_VREF_J20]
#set_property PACKAGE_PIN K16 [get_ports IO_B15_L22P_A17_K16]
#set_property PACKAGE_PIN K17 [get_ports IO_B15_L22N_A16_K17]
#set_property PACKAGE_PIN K20 [get_ports IO_B15_L19P_A22_K20]
#set_property PACKAGE_PIN L19 [get_ports IO_B15_L21P_L19]
#set_property PACKAGE_PIN L20 [get_ports IO_B15_L21N_A18_L20]

## -------------------------------------------------------------------------------------------------
## bank 16 - module connector
## -------------------------------------------------------------------------------------------------

set_property IOSTANDARD LVCMOS33 [get_ports SD_PWRn]
#set_property IOSTANDARD LVCMOS33 [get_ports SD3_Dat2]
#set_property IOSTANDARD LVCMOS33 [get_ports SD1_Dat2]
##set_property IOSTANDARD LVCMOS33 [get_ports IO_B16_L11P_SRCC_G11]
##set_property IOSTANDARD LVCMOS33 [get_ports IO_B16_L12N_MRCC_D10]
##set_property IOSTANDARD LVCMOS33 [get_ports IO_B16_L12P_MRCC_E10]
##set_property IOSTANDARD LVCMOS33 [get_ports IO_B16_L13N_MRCC_C11]
#set_property IOSTANDARD LVCMOS33 [get_ports SD3_CD]
##set_property IOSTANDARD LVCMOS33 [get_ports IO_B16_L14N_SRCC_D11]
##set_property IOSTANDARD LVCMOS33 [get_ports IO_B16_L14P_SRCC_E11]
#set_property IOSTANDARD LVCMOS33 [get_ports SD2_Dat1]
set_property IOSTANDARD LVCMOS33 [get_ports SD2_MISO]
##set_property IOSTANDARD LVCMOS33 [get_ports IO_B16_L16N_F12]
##set_property IOSTANDARD LVCMOS33 [get_ports IO_B16_L16P_G12]
##set_property IOSTANDARD LVCMOS33 [get_ports IO_B16_L17N_D13]
##set_property IOSTANDARD LVCMOS33 [get_ports IO_B16_L17P_D14]
##set_property IOSTANDARD LVCMOS33 [get_ports IO_B16_L18N_E12]
##set_property IOSTANDARD LVCMOS33 [get_ports IO_B16_L18P_E13]
##set_property IOSTANDARD LVCMOS33 [get_ports IO_B16_L19N_VREF_C13]
##set_property IOSTANDARD LVCMOS33 [get_ports IO_B16_L19P_C14]
set_property IOSTANDARD LVCMOS33 [get_ports SD2_SClk]
set_property IOSTANDARD LVCMOS33 [get_ports SD2_MOSI]
##set_property IOSTANDARD LVCMOS33 [get_ports IO_B16_L20N_B11]
##set_property IOSTANDARD LVCMOS33 [get_ports IO_B16_L20P_B12]
##set_property IOSTANDARD LVCMOS33 [get_ports IO_B16_L21N_A14]
##set_property IOSTANDARD LVCMOS33 [get_ports IO_B16_L21P_B14]
##set_property IOSTANDARD LVCMOS33 [get_ports IO_B16_L22N_A10]
##set_property IOSTANDARD LVCMOS33 [get_ports IO_B16_L22P_B10]
##set_property IOSTANDARD LVCMOS33 [get_ports IO_B16_L23N_A15]
##set_property IOSTANDARD LVCMOS33 [get_ports IO_B16_L23P_B15]
##set_property IOSTANDARD LVCMOS33 [get_ports IO_B16_L24N_A12]
##set_property IOSTANDARD LVCMOS33 [get_ports IO_B16_L24P_A13]
##set_property IOSTANDARD LVCMOS33 [get_ports IO_B16_L2N_G9]
#set_property IOSTANDARD LVCMOS33 [get_ports SD1_CSn]
#set_property IOSTANDARD LVCMOS33 [get_ports SD1_SClk]
#set_property IOSTANDARD LVCMOS33 [get_ports SD1_MISO]
#set_property IOSTANDARD LVCMOS33 [get_ports SD3_MISO]
#set_property IOSTANDARD LVCMOS33 [get_ports SD3_Dat1]
#set_property IOSTANDARD LVCMOS33 [get_ports SD1_Dat1]
#set_property IOSTANDARD LVCMOS33 [get_ports SD1_MOSI]
##set_property IOSTANDARD LVCMOS33 [get_ports IO_B16_L6N_VREF_H11]
#set_property IOSTANDARD LVCMOS33 [get_ports SD3_SClk]
#set_property IOSTANDARD LVCMOS33 [get_ports SD2_CD]
#set_property IOSTANDARD LVCMOS33 [get_ports SD1_CD]
#set_property IOSTANDARD LVCMOS33 [get_ports SD3_CSn]
#set_property IOSTANDARD LVCMOS33 [get_ports SD3_MOSI]
set_property IOSTANDARD LVCMOS33 [get_ports SD2_CSn]
#set_property IOSTANDARD LVCMOS33 [get_ports SD2_Dat2]
##set_property PACKAGE_PIN A10 [get_ports IO_B16_L22N_A10]
##set_property PACKAGE_PIN A12 [get_ports IO_B16_L24N_A12]
##set_property PACKAGE_PIN A13 [get_ports IO_B16_L24P_A13]
##set_property PACKAGE_PIN A14 [get_ports IO_B16_L21N_A14]
##set_property PACKAGE_PIN A15 [get_ports IO_B16_L23N_A15]
set_property PACKAGE_PIN A8 [get_ports SD2_CSn]
#set_property PACKAGE_PIN A9 [get_ports SD2_Dat2]
##set_property PACKAGE_PIN B10 [get_ports IO_B16_L22P_B10]
##set_property PACKAGE_PIN B11 [get_ports IO_B16_L20N_B11]
##set_property PACKAGE_PIN B12 [get_ports IO_B16_L20P_B12]
##set_property PACKAGE_PIN B14 [get_ports IO_B16_L21P_B14]
##set_property PACKAGE_PIN B15 [get_ports IO_B16_L23P_B15]
set_property PACKAGE_PIN B9 [get_ports SD_PWRn]
##set_property PACKAGE_PIN C11 [get_ports IO_B16_L13N_MRCC_C11]
#set_property PACKAGE_PIN C12 [get_ports SD3_CD]
##set_property PACKAGE_PIN C13 [get_ports IO_B16_L19N_VREF_C13]
##set_property PACKAGE_PIN C14 [get_ports IO_B16_L19P_C14]
#set_property PACKAGE_PIN C9 [get_ports SD3_Dat2]
##set_property PACKAGE_PIN D10 [get_ports IO_B16_L12N_MRCC_D10]
##set_property PACKAGE_PIN D11 [get_ports IO_B16_L14N_SRCC_D11]
##set_property PACKAGE_PIN D13 [get_ports IO_B16_L17N_D13]
##set_property PACKAGE_PIN D14 [get_ports IO_B16_L17P_D14]
#set_property PACKAGE_PIN D8 [get_ports SD3_CSn]
#set_property PACKAGE_PIN D9 [get_ports SD3_MOSI]
##set_property PACKAGE_PIN E10 [get_ports IO_B16_L12P_MRCC_E10]
##set_property PACKAGE_PIN E11 [get_ports IO_B16_L14P_SRCC_E11]
##set_property PACKAGE_PIN E12 [get_ports IO_B16_L18N_E12]
##set_property PACKAGE_PIN E13 [get_ports IO_B16_L18P_E13]
#set_property PACKAGE_PIN F10 [get_ports SD1_Dat2]
##set_property PACKAGE_PIN F12 [get_ports IO_B16_L16N_F12]
#set_property PACKAGE_PIN F13 [get_ports SD2_Dat1]
set_property PACKAGE_PIN F14 [get_ports SD2_MISO]
#set_property PACKAGE_PIN F8 [get_ports SD2_CD]
#set_property PACKAGE_PIN F9 [get_ports SD1_CD]
#set_property PACKAGE_PIN G10 [get_ports SD1_CSn]
##set_property PACKAGE_PIN G11 [get_ports IO_B16_L11P_SRCC_G11]
##set_property PACKAGE_PIN G12 [get_ports IO_B16_L16P_G12]
#set_property PACKAGE_PIN G14 [get_ports SD1_Dat1]
##set_property PACKAGE_PIN G9 [get_ports IO_B16_L2N_G9]
##set_property PACKAGE_PIN H11 [get_ports IO_B16_L6N_VREF_H11]
#set_property PACKAGE_PIN H12 [get_ports SD3_SClk]
#set_property PACKAGE_PIN H13 [get_ports SD1_SClk]
#set_property PACKAGE_PIN H14 [get_ports SD1_MISO]
set_property PACKAGE_PIN H8 [get_ports SD2_SClk]
set_property PACKAGE_PIN H9 [get_ports SD2_MOSI]
#set_property PACKAGE_PIN J10 [get_ports SD3_MISO]
#set_property PACKAGE_PIN J11 [get_ports SD3_Dat1]
#set_property PACKAGE_PIN J13 [get_ports SD1_MOSI]

# -------------------------------------------------------------------------------------------------
# timing constraints
# -------------------------------------------------------------------------------------------------


# All timing constraint translations are rough conversions, intended to act as a template for further manual refinement. The translations should not be expected to produce semantically identical results to the original ucf. Each xdc timing constraint must be manually inspected and verified to ensure it captures the desired intent

# create_clock -period 5.000 -name sys_clock_pin [get_ports clock_200MHz_p]
set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets Clock_Generator/inst/clk_in1_Master_Clock_Divider]

# -------------------------------------------------------------------------------------------------
# eof
# -------------------------------------------------------------------------------------------------



set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.STARTUP.STARTUPCLK JTAGCLK [current_design]
